---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmCharts:
  - includeCRDs: true
    name: otel-integration
    releaseName: coralogix-otel
    repo: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
    valuesFile: ./values.yaml
    version: 0.0.126