---
global:
  domain: "coralogix.com"
  clusterName: "otel-local"
  defaultApplicationName: "otel"
  defaultSubsystemName: "integration" 
  logLevel: "warn"
  collectionInterval: "30s"
  gatewayEndpoint: "REPLACE_WITH_GATEWAY_ENDPOINT"

opentelemetry-agent:
  enabled: true
  mode: daemonset
  
  config:
    receivers:
      hostmetrics:
        collection_interval: "{{ .Values.global.collectionInterval }}"
        scrapers:
          cpu:
          memory:
          filesystem:
          disk:
          load:
          network:
          process:
      
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: connection

      batch:
        timeout: 1s
        send_batch_size: 1024

      resource:
        attributes:
          - key: sample.agent
            value: "true"
            action: upsert

    exporters:
      otlp:
        endpoint: "{{ .Values.global.gatewayEndpoint }}"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [hostmetrics]
          processors: [k8sattributes, resource, batch]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [k8sattributes, resource, batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [k8sattributes, resource, batch]
          exporters: [otlp]

opentelemetry-cluster-collector:
  enabled: true
  mode: deployment
  replicaCount: 1
  
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      
      resource:
        attributes:
          - key: sample.collector
            value: "true" 
            action: upsert

    exporters:
      otlp:
        endpoint: "{{ .Values.global.gatewayEndpoint }}"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlp]

opentelemetry-agent-windows:
  enabled: false